Add option to load a fixed number of levels sequentially
AlignmentResearch/envpool pull request #1
Opened 2024-02-29 15:17 UTC by taufeeque9

2024-03-01 21:01 UTC, rhaps0dy requested changes
Looks pretty good overall, left some comments that should change.

2024-03-01 21:01 UTC, rhaps0dy commented on envpool/sokoban/level_loader.cc
> +    std::uniform_int_distribution<size_t> load_file_idx_r(
Needs `static_assert(std::is_same_v<std::size_t, unsigned> || std::is_same_v<std::size_t, unsigned long> || std::is_same_v<std::size_t, unsigned long long>)` (https://stackoverflow.com/questions/77380145/is-stduniform-int-distributionstdsize-t-undefined-behavior)

In fact we should create a `template<typename T> safe_uniform_int<T>(... args)` which checks bounds and does the `static_assert` to be sure.

2024-03-01 21:01 UTC, rhaps0dy commented on envpool/sokoban/level_loader.cc
> +  cur_file = level_file_paths.begin();
You should initialize this in the constructor list above, like `cur_level` (see https://stackoverflow.com/a/9903262/4521118)

2024-03-01 21:01 UTC, rhaps0dy commented on envpool/sokoban/level_loader.cc
> +const std::string PRINT_LEVEL_KEY = "# .a$@s";
Thanks, this was wrong. Maybe we should have a test that asserts that `PrintLevel` and `LoadNewFile` round-trip? Not in this PR though.

2024-03-01 21:01 UTC, rhaps0dy commented on envpool/sokoban/sokoban_py_envpool_test.py
> +import py
the py library[ is in maintenance mode and should not be used in new code](https://pypi.org/project/py/)

2024-03-01 21:01 UTC, rhaps0dy commented on envpool/sokoban/level_loader.cc
> +  if (n_levels_to_load > 0 && levels_loaded >= n_levels_to_load) {
What's the intended way to reset the level counter, just create a new environment? Makes sense

2024-03-01 21:01 UTC, rhaps0dy commented on envpool/sokoban/level_loader.cc
> +#include <pybind11/iostream.h>
Why do you need this as opposed to `<iostream>`? Is it so that `StdCapture` below works?

2024-03-01 21:01 UTC, rhaps0dy commented on envpool/sokoban/sokoban_py_envpool_test.py
> +import py
[Use Pytest instead](https://github.com/pytest-dev/py/issues/288). 

https://docs.pytest.org/en/7.1.x/how-to/capture-stdout-stderr.html#accessing-captured-output-from-a-test-function

2024-03-04 09:58 UTC, taufeeque9 commented on envpool/sokoban/level_loader.cc
> +  cur_file = level_file_paths.begin();
I had initialised it in the constructor list before just like `cur_file` with `cur_file(level_file_paths.begin())` but the code was resulting in segmentation faults. After initializing it inside the constructor, the code was working fine. I'm guessing it had something to do with `cur_file` being a vector of `std::filesystem::path`.

2024-03-04 09:59 UTC, taufeeque9 commented on envpool/sokoban/level_loader.cc
> +const std::string PRINT_LEVEL_KEY = "# .a$@s";
I'll add it through a separate PR

2024-03-04 10:02 UTC, taufeeque9 commented on envpool/sokoban/level_loader.cc
> +#include <pybind11/iostream.h>
It is not needed. I was experimenting with a different way of printing that could be easier during tests with python but it didn't end up working as I wanted. I'll remove the import.

2024-03-04 11:14 UTC, taufeeque9 commented on envpool/sokoban/level_loader.cc
> +  if (n_levels_to_load > 0 && levels_loaded >= n_levels_to_load) {
I think we can do that or provide a method to reset the level counter. What do you think?

2024-03-04 14:25 UTC, taufeeque9 commented on envpool/sokoban/level_loader.cc
> +    std::uniform_int_distribution<size_t> load_file_idx_r(
Added the `safe_uniform_int` function

2024-03-04 14:25 UTC, taufeeque9 commented on envpool/sokoban/sokoban_py_envpool_test.py
> +import py
Done

2024-03-04 16:24 UTC, rhaps0dy approved these changes

2024-03-04 16:24 UTC, rhaps0dy commented on envpool/sokoban/level_loader.cc
> +  cur_file = level_file_paths.begin();
Hm, maybe UB elsewhere in the program was causing this? I'm willing to drop the issue.

2024-03-04 16:24 UTC, rhaps0dy commented on envpool/sokoban/level_loader.cc
> +const std::string PRINT_LEVEL_KEY = "# .a$@s";
Not clear that we actually need it tbh

2024-03-04 16:24 UTC, rhaps0dy commented on envpool/sokoban/level_loader.cc
> +  if (n_levels_to_load > 0 && levels_loaded >= n_levels_to_load) {
Then it needs to be callable through Python, which needs extra complication. I think it's fine like you already wrote it.

2024-03-04 16:24 UTC, rhaps0dy commented on envpool/sokoban/utils.h
> +
oh no we duplicated again, see #3 

I like this version better but it'll need to pass linters later on

2024-03-08 00:12 UTC, merged